export const state = {
    map: null,
    userMarker: null,
    userLocation: null,
    gpsAccuracy: null,
    gpsLastFixAt: null,
    gpsStatus: 'idle',
    gpsRequestToken: 0,
    watchId: null,
    compassHeading: null,
    compassEnabled: false,
    compassListener: null,
    compassPermissionTried: false,
    hasLocatedUser: false,
    routeGeometry: null,
    proximityCircle: null,
    stations: [],
    events: [],
    markers: [],
    isAdmin: false,
    activeStationId: null,
    activeEventId: null,
    activeTab: "map",
    favorites: new Set(),
    downloads: { flyer1: '', flyer2: '', icsDate: '' },
    config: {
        title: 'LICHTERNACHT',
        subtitle: 'Bechhofen | 22. Nov'
    },
    useLocalStorage: false,
    db: null,
    firebaseApiKey: '',
    auth: null,
    appId: null,
    // Firebase functions container
    fb: {}
};
